### PR TITLE
updated code for the 2022 season

### PR DESCRIPTION
**Pull request by realdiegopoptart**

### CODE REVIEW

**Comment by tjquillan** [comment]
It doesn't look like `2022aztem` is a valid event to blue alliance. Is this intentional?

https://www.thebluealliance.com/event/2022aztem

**Comment by atramirez** [comment]
@realdiegopoptart `aztem` has changed now that it is AZ Valley Regional. The best way to find the new code is going to www.thebluealliance.com finding the event. At the end of the url there will be the event id used in the API.

**Comment by realdiegopoptart** [comment]
alright, will update the code. One of the officers told me to leave it as ``aztem`` until he got more information about it.

**Review by atramirez — CHANGES_REQUESTED** [review]
You need to also change `2022aztem.json` to the new name for the site to work properly. It will be searching for `2022azva.json`.

**Pull request merged**
